//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mageki.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mageki.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Absolute 的本地化字符串。
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aime ID 的本地化字符串。
        /// </summary>
        public static string AimeID {
            get {
                return ResourceManager.GetString("AimeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use DEVICE\aime.txt 的本地化字符串。
        /// </summary>
        public static string AimeIDPlaceHolder {
            get {
                return ResourceManager.GetString("AimeIDPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anti-Mis-Touch 的本地化字符串。
        /// </summary>
        public static string AntiMisTouch {
            get {
                return ResourceManager.GetString("AntiMisTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan your AIC Card or cancel to emulate card reading. 的本地化字符串。
        /// </summary>
        public static string BeginNfcSessionAlert {
            get {
                return ResourceManager.GetString("BeginNfcSessionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button bottom margin 的本地化字符串。
        /// </summary>
        public static string ButtonBottomMargin {
            get {
                return ResourceManager.GetString("ButtonBottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check update failed 的本地化字符串。
        /// </summary>
        public static string CheckUpdateFailed {
            get {
                return ResourceManager.GetString("CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection 的本地化字符串。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t remind me again 的本地化字符串。
        /// </summary>
        public static string DoNotRemindMeAgain {
            get {
                return ResourceManager.GetString("DoNotRemindMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Composite Mode 的本地化字符串。
        /// </summary>
        public static string EnableCompositeMode {
            get {
                return ResourceManager.GetString("EnableCompositeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Haptic Feedback 的本地化字符串。
        /// </summary>
        public static string EnableHapticFeedback {
            get {
                return ResourceManager.GetString("EnableHapticFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Lever Overflow Handling 的本地化字符串。
        /// </summary>
        public static string EnableLeverOverflowHandling {
            get {
                return ResourceManager.GetString("EnableLeverOverflowHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gameplay 的本地化字符串。
        /// </summary>
        public static string Gameplay {
            get {
                return ResourceManager.GetString("Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to release page 的本地化字符串。
        /// </summary>
        public static string GoToReleasePage {
            get {
                return ResourceManager.GetString("GoToReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Game Buttons 的本地化字符串。
        /// </summary>
        public static string HideGameButtons {
            get {
                return ResourceManager.GetString("HideGameButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Menu Buttons 的本地化字符串。
        /// </summary>
        public static string HideMenuButtons {
            get {
                return ResourceManager.GetString("HideMenuButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Wall Action Devices 的本地化字符串。
        /// </summary>
        public static string HideWallActionDevices {
            get {
                return ResourceManager.GetString("HideWallActionDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Address 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard 的本地化字符串。
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lever And W.A.D 的本地化字符串。
        /// </summary>
        public static string LeverAndWAD {
            get {
                return ResourceManager.GetString("LeverAndWAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lever Linearity 的本地化字符串。
        /// </summary>
        public static string LeverLinearity {
            get {
                return ResourceManager.GetString("LeverLinearity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lever Move Mode 的本地化字符串。
        /// </summary>
        public static string LeverMoveMode {
            get {
                return ResourceManager.GetString("LeverMoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lever Sensitivity 的本地化字符串。
        /// </summary>
        public static string LeverSensitivity {
            get {
                return ResourceManager.GetString("LeverSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mageki is up to date 的本地化字符串。
        /// </summary>
        public static string MagekiIsUpToDate {
            get {
                return ResourceManager.GetString("MagekiIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version available 的本地化字符串。
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program crashed unexpectedly! 的本地化字符串。
        /// </summary>
        public static string ProgramCrashedUnexpectedly {
            get {
                return ResourceManager.GetString("ProgramCrashedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol 的本地化字符串。
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relative 的本地化字符串。
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Button 的本地化字符串。
        /// </summary>
        public static string ServiceButton {
            get {
                return ResourceManager.GetString("ServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Button 的本地化字符串。
        /// </summary>
        public static string TestButton {
            get {
                return ResourceManager.GetString("TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
