//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mageki.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mageki.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aime ID.
        /// </summary>
        public static string AimeID {
            get {
                return ResourceManager.GetString("AimeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use DEVICE\aime.txt.
        /// </summary>
        public static string AimeIDPlaceHolder {
            get {
                return ResourceManager.GetString("AimeIDPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan your AIC Card or cancel to emulate card reading..
        /// </summary>
        public static string BeginNfcSessionAlert {
            get {
                return ResourceManager.GetString("BeginNfcSessionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button bottom margin.
        /// </summary>
        public static string ButtonBottomMargin {
            get {
                return ResourceManager.GetString("ButtonBottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check update failed.
        /// </summary>
        public static string CheckUpdateFailed {
            get {
                return ResourceManager.GetString("CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t remind me again.
        /// </summary>
        public static string DoNotRemindMeAgain {
            get {
                return ResourceManager.GetString("DoNotRemindMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Composite Mode.
        /// </summary>
        public static string EnableCompositeMode {
            get {
                return ResourceManager.GetString("EnableCompositeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Haptic Feedback.
        /// </summary>
        public static string EnableHapticFeedback {
            get {
                return ResourceManager.GetString("EnableHapticFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        public static string Gameplay {
            get {
                return ResourceManager.GetString("Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to release page.
        /// </summary>
        public static string GoToReleasePage {
            get {
                return ResourceManager.GetString("GoToReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Game Buttons.
        /// </summary>
        public static string HideGameButtons {
            get {
                return ResourceManager.GetString("HideGameButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Menu Buttons.
        /// </summary>
        public static string HideMenuButtons {
            get {
                return ResourceManager.GetString("HideMenuButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Wall Action Devices.
        /// </summary>
        public static string HideWallActionDevices {
            get {
                return ResourceManager.GetString("HideWallActionDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lever And W.A.D.
        /// </summary>
        public static string LeverAndWAD {
            get {
                return ResourceManager.GetString("LeverAndWAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lever Linearity.
        /// </summary>
        public static string LeverLinearity {
            get {
                return ResourceManager.GetString("LeverLinearity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lever Move Mode.
        /// </summary>
        public static string LeverMoveMode {
            get {
                return ResourceManager.GetString("LeverMoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lever Sensitivity.
        /// </summary>
        public static string LeverSensitivity {
            get {
                return ResourceManager.GetString("LeverSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mageki is up to date.
        /// </summary>
        public static string MagekiIsUpToDate {
            get {
                return ResourceManager.GetString("MagekiIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program crashed unexpectedly!.
        /// </summary>
        public static string ProgramCrashedUnexpectedly {
            get {
                return ResourceManager.GetString("ProgramCrashedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Button.
        /// </summary>
        public static string ServiceButton {
            get {
                return ResourceManager.GetString("ServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Button.
        /// </summary>
        public static string TestButton {
            get {
                return ResourceManager.GetString("TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
