//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mageki.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mageki.Resources.AppResources.zh", typeof(AppResources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绝对.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aime 卡号.
        /// </summary>
        public static string AimeID {
            get {
                return ResourceManager.GetString("AimeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 DEVICE\aime.txt.
        /// </summary>
        public static string AimeIDPlaceHolder {
            get {
                return ResourceManager.GetString("AimeIDPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防误触（实验）.
        /// </summary>
        public static string AntiMisTouch {
            get {
                return ResourceManager.GetString("AntiMisTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扫描Aime卡片，或取消以模拟刷卡。.
        /// </summary>
        public static string BeginNfcSessionAlert {
            get {
                return ResourceManager.GetString("BeginNfcSessionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按钮下边距.
        /// </summary>
        public static string ButtonBottomMargin {
            get {
                return ResourceManager.GetString("ButtonBottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新失败。.
        /// </summary>
        public static string CheckUpdateFailed {
            get {
                return ResourceManager.GetString("CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已连接.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未连接.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不再提醒.
        /// </summary>
        public static string DoNotRemindMeAgain {
            get {
                return ResourceManager.GetString("DoNotRemindMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 融合模式.
        /// </summary>
        public static string EnableCompositeMode {
            get {
                return ResourceManager.GetString("EnableCompositeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触摸反馈.
        /// </summary>
        public static string EnableHapticFeedback {
            get {
                return ResourceManager.GetString("EnableHapticFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏性.
        /// </summary>
        public static string Gameplay {
            get {
                return ResourceManager.GetString("Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前往发布页.
        /// </summary>
        public static string GoToReleasePage {
            get {
                return ResourceManager.GetString("GoToReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏按钮.
        /// </summary>
        public static string HideGameButtons {
            get {
                return ResourceManager.GetString("HideGameButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏菜单按钮.
        /// </summary>
        public static string HideMenuButtons {
            get {
                return ResourceManager.GetString("HideMenuButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏墙键.
        /// </summary>
        public static string HideWallActionDevices {
            get {
                return ResourceManager.GetString("HideWallActionDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 键盘.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摇杆与侧键.
        /// </summary>
        public static string LeverAndWAD {
            get {
                return ResourceManager.GetString("LeverAndWAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摇杆线性度.
        /// </summary>
        public static string LeverLinearity {
            get {
                return ResourceManager.GetString("LeverLinearity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摇杆移动模式.
        /// </summary>
        public static string LeverMoveMode {
            get {
                return ResourceManager.GetString("LeverMoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 摇杆灵敏度.
        /// </summary>
        public static string LeverSensitivity {
            get {
                return ResourceManager.GetString("LeverSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mageki已是最新版。.
        /// </summary>
        public static string MagekiIsUpToDate {
            get {
                return ResourceManager.GetString("MagekiIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新版本可用.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其它.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序异常退出！.
        /// </summary>
        public static string ProgramCrashedUnexpectedly {
            get {
                return ResourceManager.GetString("ProgramCrashedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 协议.
        /// </summary>
        public static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相对.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service键.
        /// </summary>
        public static string ServiceButton {
            get {
                return ResourceManager.GetString("ServiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test键.
        /// </summary>
        public static string TestButton {
            get {
                return ResourceManager.GetString("TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
